' Centralized references to shared graphical assets (9-patches, icons, etc.)

namespace Assets
    const NINE_PATCH_ROUNDED_6 = "pkg:/images/ui/rounded_6.9.png"
    const NINE_PATCH_ROUNDED_8 = "pkg:/images/ui/rounded_8.9.png"
    const NINE_PATCH_ROUNDED_10 = "pkg:/images/ui/rounded_10.9.png"
    const NINE_PATCH_ROUNDED_12 = "pkg:/images/ui/rounded_12.9.png"
    const NINE_PATCH_ROUNDED_14 = "pkg:/images/ui/rounded_14.9.png"

    const FOCUS_OUTLINE_BRAND = "pkg:/images/ui/outline_gradient_8.9.png"
    const FOCUS_OUTLINE_NEUTRAL = "pkg:/images/ui/outline.9.png"
    const FOCUS_OUTLINE_HD = "pkg:/images/ui/outline_hd.9.png"
    const FOCUS_OUTLINE_FHD = "pkg:/images/ui/outline_fhd.9.png"

    const BACKGROUND_GLOW = "pkg:/images/background/bg3.png"
    const BACKGROUND_BG1 = "pkg:/images/background/bg1.jpg"
    const BACKGROUND_BG2 = "pkg:/images/background/bg2.jpg"

    const VIGNETTE_RADIAL = "pkg:/images/overlays/vignette-radial.png"

    const MOVIE_MASK = "pkg:/images/ui/movieMask.png"
    const MUSIC_MASK = "pkg:/images/ui/musicMask.png"
    const WIDE_MASK = "pkg:/images/ui/wideMask.png"

end namespace
