import "pkg:/source/enums/ColorPalette.bs"
import "pkg:/source/utils/misc.bs"

sub init()
    m.unplayedNumber = m.top.findNode("unplayedNumber")
    m.checkmark = m.top.findNode("checkmark")
    m.badgeBackground = m.top.findNode("badgeBackground")

    m.checkmark.font.size = 36
    m.checkmark.visible = false
    m.unplayedNumber.visible = false
    m.badgeBackground.visible = false
end sub

sub onDataChange()
    m.badgeBackground.visible = false
    m.checkmark.visible = false
    m.unplayedNumber.visible = false

    if not isValidAndNotEmpty(m.top.data) then return

    if chainLookupReturn(m.top.data, "unplayedCount", 0) > 0
        disableUnwatchedEpisodeCount = chainLookupReturn(m.global.session, "user.settings.`ui.tvshows.disableUnwatchedEpisodeCount`", false)
        if disableUnwatchedEpisodeCount then return

        unplayedCount = m.top.data.unplayedCount.ToStr()
        unplayedCountLength = len(unplayedCount)

        m.badgeBackground.blendColor = ColorPalette.OCELOTL_ACCENT
        m.badgeBackground.visible = true

        if isValid(m.unplayedNumber)
            m.unplayedNumber.font.size = unplayedCountLength = 4 ? 25 : 30
            m.unplayedNumber.visible = true
            m.unplayedNumber.text = unplayedCount
        end if
        return
    end if

    if not chainLookupReturn(m.top.data, "showWatchedCheckmark", true) then return

    if chainLookupReturn(m.top.data, "played", false)
        m.badgeBackground.blendColor = ColorPalette.OCELOTL_ACCENT
        m.badgeBackground.visible = true
        if isValid(m.checkmark)
            m.checkmark.visible = true
        end if
        return
    end if
end sub
