import "pkg:/source/enums/ColorPalette.bs"
import "pkg:/source/enums/String.bs"
import "pkg:/source/utils/misc.bs"

sub init()
    m.name = m.top.findNode("label")
    m.buttonBackground = m.top.findNode("buttonBackground")
    m.valueFocusOutline = m.top.findNode("valueFocusOutline")
    m.value = m.top.findNode("value")
    m.value.backgroundUri = "pkg:/images/transparent.png"

    m.name.color = ColorPalette.OCELOTL_TEXT_MUTED
    m.value.textColor = ColorPalette.OCELOTL_TEXT
    m.value.hintTextColor = ColorPalette.OCELOTL_TEXT_DIM
    m.buttonBackground.blendColor = ColorPalette.OCELOTL_CARD_BG
    m.valueFocusOutline.blendColor = ColorPalette.OCELOTL_FOCUS_OUTLINE

    m.value.hintText = tr("Enter a username")
    m.value.maxTextLength = 120
end sub

sub itemContentChanged()
    data = m.top.itemContent

    m.name.text = data.label
    if isStringEqual(data.type, "password")
        m.value.hintText = tr("Enter a password")
        m.value.secureMode = true
    end if

    m.value.text = data.value
end sub

sub onItemHasFocusChange()
    m.valueFocusOutline.visible = m.top.itemHasFocus
end sub
