import "pkg:/source/enums/ColorPalette.bs"
import "pkg:/source/enums/String.bs"
import "pkg:/source/utils/misc.bs"

sub init()
    m.hint = m.top.findNode("hint")

    m.value = m.top.findNode("value")
    m.value.backgroundUri = "pkg:/images/transparent.png"
    m.value.width = 440

    m.value.observeField("text", "onTextChanged")

    m.value.textColor = ColorPalette.OCELOTL_TEXT_PRIMARY
    m.hint.color = ColorPalette.OCELOTL_TEXT_SECONDARY

    m.hint.text = tr("Enter a username")
    m.value.maxTextLength = 120

    m.buttonBackground = m.top.findNode("buttonBackground")
    m.buttonBackground.blendColor = ColorPalette.OCELOTL_CARD
end sub

sub itemContentChanged()
    data = m.top.itemContent

    if isStringEqual(data.type, "password")
        m.hint.text = tr("Enter a password")
        m.value.secureMode = true
    else
        m.hint.text = tr("Enter a username")
        m.value.secureMode = false
    end if

    m.value.text = data.value
    onTextChanged()
end sub

sub onTextChanged()
    m.hint.visible = (m.value.text = "")
end sub

sub onFocusChanged()
    if m.top.itemHasFocus
        m.buttonBackground.blendColor = ColorPalette.OCELOTL_ACCENT
    else
        m.buttonBackground.blendColor = ColorPalette.OCELOTL_CARD
    end if
end sub
