import "pkg:/source/enums/ColorPalette.bs"
import "pkg:/source/utils/misc.bs"

sub init()
    m.poster = m.top.findNode("poster")
    m.background = m.top.findNode("background")
    m.name = m.top.findNode("name")
    m.baseUrl = m.top.findNode("baseUrl")
    m.labels = m.top.findNode("labels")

    m.serverCard = m.top.findNode("serverCard")
    m.serverCard.blendColor = ColorPalette.OCELOTL_CARD_BG

    m.trashContainer = m.top.findNode("trashContainer")
    m.trashContainer.color = ColorPalette.TRANSPARENT

    m.trashBackground = m.top.findNode("trashBackground")
    m.trashBackground.blendColor = ColorPalette.OCELOTL_CARD_BG

    m.trash = m.top.findNode("trash")
    m.trashFocus = m.top.findNode("trashFocus")

    m.focusIndicator = m.top.findNode("focusIndicator")
    m.focusIndicator.visible = m.top.itemHasFocus

    m.background.color = ColorPalette.TRANSPARENT

    setTextColor()
end sub
sub itemContentChanged()
    server = m.top.itemContent

    if isValid(server)
        server.observeField("itemHasDeleteFocus", "onDeleteFocusChanged")
    end if

    m.poster.uri = server.iconUrl
    m.name.text = server.name
    m.baseUrl.text = server.baseUrl

    setTrashIconVisibility()
    setDeleteFocus()
end sub

sub onDeleteFocusChanged()
    setDeleteFocus()
    setFocusIndicator()
end sub

sub setTrashIconVisibility()
    if not isValid(m.top.itemContent) then return
    if not isValid(m.top.itemContent.isSavedServer) then return

    m.trashContainer.visible = m.top.itemContent.isSavedServer
end sub

sub onItemHasFocusChange()
    if not m.top.itemHasFocus
        m.top.itemContent.itemHasDeleteFocus = false
    end if

    setDeleteFocus()
    setFocusIndicator()
end sub

sub setDeleteFocus()
    if not isValid(m.trashFocus) then return
    if not isValid(m.top.itemContent) then return

    hasDeleteFocus = chainLookupReturn(m.top.itemContent, "itemHasDeleteFocus", false)

    m.trashFocus.visible = hasDeleteFocus
end sub

sub setFocusIndicator()
    if isValid(m.focusIndicator)
        hasDeleteFocus = false

        if isValid(m.top.itemContent)
            hasDeleteFocus = chainLookupReturn(m.top.itemContent, "itemHasDeleteFocus", false)
        end if

        m.focusIndicator.visible = m.top.itemHasFocus and not hasDeleteFocus
    end if
end sub

sub setTextColor()
    textColor = ColorPalette.WHITE

    children = m.labels.getChildren(-1, 0)
    for each child in children
        child.color = textColor
    end for
end sub
