import "pkg:/source/enums/ColorPalette.bs"
import "pkg:/source/utils/misc.bs"

sub init()
    m.background = m.top.findNode("background")
    m.serverIcon = m.top.findNode("serverIcon")
    m.name = m.top.findNode("name")
    m.baseUrl = m.top.findNode("baseUrl")
    m.trash = m.top.findNode("trash")

    ' Default state — no focus
    m.background.blendColor = ColorPalette.TRANSPARENT
    m.name.color = ColorPalette.WHITE
    m.baseUrl.color = ColorPalette.OCELOTL_TEXT_SECONDARY
end sub

sub itemContentChanged()
    server = m.top.itemContent
    m.serverIcon.uri = "pkg:/images/ocelotl/icons/ui/server-icon.png"
    m.name.text = server.name
    m.baseUrl.text = server.baseUrl
    setTrashIconVisibility()
    setBackground()
end sub

sub setTrashIconVisibility()
    if not isValid(m.top.itemContent) then return
    if not isValid(m.top.itemContent.isSavedServer) then return
    m.trash.visible = m.top.itemContent.isSavedServer
end sub

sub onItemHasFocusChange()
    if not m.top.itemHasFocus
        m.top.itemContent.itemHasDeleteFocus = false
    end if
    setBackground()
end sub

sub setBackground()
    if not isValid(m.top.itemContent) then return
    if not isValid(m.top.itemContent.itemHasDeleteFocus) then return

    if m.top.itemContent.itemHasDeleteFocus
        m.background.blendColor = ColorPalette.RED
        return
    end if

    if m.top.itemHasFocus
        m.background.blendColor = ColorPalette.OCELOTL_ACCENT
    else
        m.background.blendColor = ColorPalette.TRANSPARENT
    end if
end sub
