import "pkg:/source/enums/ColorPalette.bs"
import "pkg:/source/utils/misc.bs"
import "pkg:/source/utils/theme.bs"

sub init()
    findNodes()
    applyTheme()
end sub

sub findNodes()
    m.poster = m.top.findNode("poster")
    m.background = m.top.findNode("background")
    m.name = m.top.findNode("name")
    m.baseUrl = m.top.findNode("baseUrl")
    m.labels = m.top.findNode("labels")
    m.trashWrapper = m.top.findNode("trashWrapper")
    m.trash = m.top.findNode("trash")
end sub

sub applyTheme()
    setTextColors()
    setTrashIconVisibility()
    setBackground()
end sub

sub setTextColors()
    m.name.color = m.global.theme.TEXT_PRIMARY
    m.baseUrl.color = m.global.theme.TEXT_PRIMARY
end sub

sub itemContentChanged()
    server = m.top.itemContent
    m.name.text = server.name
    m.baseUrl.text = server.baseUrl

    applyTheme()
end sub

sub setTrashIconVisibility()
    if not isValid(m.top.itemContent) then return
    if not isValid(m.top.itemContent.isSavedServer) then return

    m.trashWrapper.visible = m.top.itemContent.isSavedServer
end sub

sub onItemHasFocusChange()
    if not isValid(m.top.itemContent) then return
    if not isValid(m.top.itemContent.itemHasDeleteFocus) then return

    applyTheme()
end sub

sub setBackground()
    if not isValid(m.top.itemContent) then return
    if not isValid(m.top.itemContent.itemHasDeleteFocus) then return

    if m.top.itemContent.itemHasDeleteFocus
        m.name.color = m.global.theme.TEXT_MUTED
        m.baseUrl.color = m.global.theme.TEXT_MUTED
        m.trash.blendColor = m.global.theme.DELETE_FOCUS
        return
    end if

    m.trash.blendColor = m.global.theme.ICON_DEFAULT
    setTextColors()
end sub
